### ISSUE TITLE
Ejercicio e) 13.

### ISSUE THREAD

**Issue by mateo-astudillo** [mateo-astudillo/tp-c#4]
Se pide cargar en una matriz las notas de matemáticas de los alumnos de 
secundaria de una escuela. Suponiendo que hay 2 grados distintos, 5 alumnos 
por grado, se pide:
i. Ingresar las notas que ha sacado cada alumno de cada grado.
ii. Imprimir cuál es la nota promedio de cada grado.
iii. Imprimir la mayor nota en general.
iv. Imprimir todas las notas.
v. Imprimir cuántos alumnos aprobaron (sacaron mayor a 7) y 
cuántos reprobaron de cada grado

**Comment by StivenCodess** [comment]
Oh rigth, it's all okei brother 😋🤙
